### PR TITLE
feat: code editor support for dark them

### PR DESCRIPTION
**Pull request by sravimohan**
- adds support for dark theme to the code editor
- fixes toolbar rounding

### CODE REVIEW

**Comment by petyosi** [comment]
Hi, 

this is a necessary addition, indeed. However, rather than binding that behavior to a hard-coded CSS class of the main editor, I would rather expose the theme as a parameter for the diffSourcePlugin. Let me know if this makes sense. If not, I'm going to get to that quite soon.

**Comment by sravimohan** [comment]
Hi @petyosi, I will not be able to work on this in the short term. Please go ahead when you can

**Comment by Melvynx** [comment]
Hi @sravimohan and @petyosi, I made the fix in the branch : https://github.com/mdx-editor/editor/pull/141. I really need it for my current app x)

**Comment by petyosi** [comment]
@sravimohan - let me know if the approach I've taken works for you. Thanks!

**Pull request closed without merging**
