### PR TITLE
feat: Add aria-label to CreateLink button

### LINKED ISSUE #493: Improve Accessibility of CreateLink and LinkPlugin
The Link button in the toolbar and the popup that appears after clicking it both lack an aria-label. Labels need to be added for writing test cases and making the library accessible to screen readers.

### PR DESCRIPTION
**Pull request by dharanish-v**
Added aria-label to improve accessibility

closes #493

### CODE REVIEW

**Comment by petyosi** [comment]
This should use the translation I believe?

**Comment by dharanish-v** [comment]
> This should use the translation I believe?

I have few more changes to this PR, I will push those in an hour

**Comment by dharanish-v** [comment]
> > This should use the translation I believe?
> 
> I have few more changes to this PR, I will push those in an hour

done

**Comment by dharanish-v** [comment]
> This should use the translation I believe?

can we merge this by today ?

**Comment by petyosi** [comment]
No. It fails the prettier check. I will add the change as a part of a larger commit.

**Comment by dharanish-v** [comment]
> No. It fails the prettier check. I will add the change as a part of a larger commit.

I need this change for a task,  deadline is tomorrow, how can i check for prettier in local ?, because in github i don't see any checks running.

**Comment by dharanish-v** [comment]
> No. It fails the prettier check. I will add the change as a part of a larger commit.

I have made the changes, now it won't fail, kindly check because i need this for a task as soon as possible.

**Pull request merged**
