### PR TITLE
feat: Add Image upload to server

### PR DESCRIPTION
**Pull request by mrwan200**
Hi, Thank for making awesome markdown editor.

I made image uploader into server in `InsertImage` function. 😃

Here some screenshot
- Insert image modal
image

- After insert image
Screenshot 2566-09-15 at 16 20 56

Thanks!

### CODE REVIEW

**Comment by petyosi** [comment]
I like that! I also saw that the image dialog has some regressions visually. Will look into merging this.

**Comment by petyosi** [comment]
I reviewed the code - the DialogButton form is meant to be a generic one-field input text dialog that can be used for various purposes. It's not suitable to inject image-specific logic in there. 

I do understand why you've done your modifications in there, though - it's not trivial to achieve the behavior without copy/pasting a lot of code. 

Let me think of how this can be done in a better way. Perhaps I should expose more toolbar primitives to make that easier. Will leave this open, as the feature itself is worth it.

**Comment by kushul** [comment]
Hi,
I need this feature of image uploader. When will this be available please?

**Comment by petyosi** [comment]
@kushul @mrwan200 I made a round of improvements in the dialogs, the image dialog now includes an upload button. Give it a try. Thank you for your effort!

**Comment by petyosi** [comment]
@kushul feel free to fork the project or take the plugin I've created and adjust it to your liking. I'm afraid I don't have the capability to support your project requirements to such specifics and level of involvement on my side.

**Comment by kushul** [comment]
yes sure @petyosi. Anything about the documentation of the image uploader?

**Pull request closed without merging**
