### PR TITLE
chore(deps): update lexical packages

### PR DESCRIPTION
**Pull request by david10sing**
### Description
This PR is to upgrade lexical to latest version - 0.14.2.

I am working in a remix monorepo project with ESM on and getting errors stating `lexical` being CJS

image

Lexical is already on v0.14.2 which has esm support.

I've tried installing locally from file but it is still complaining about the CJS issue but it might also be due to pnpm workspace.

### CODE REVIEW

**Comment by david10sing** [comment]
@petyosi 

Thank you for reviewing. 🙏

**Comment by petyosi** [comment]
@david10sing - thank you very much, the upgrade is indeed necessary. To ensure that I'm not missing something, please let me know the testing you did after the upgrade. Sometimes there are errors like incompatible types, etc.

**Comment by david10sing** [comment]
Hi @petyosi 

I ran the ladle build and did a quick smoke test locally. There was no apparent error on the build and in browser.

I also did a build and there was no error.

Let me know if there needs to be further testing and I will do it.

Cheers

**Comment by petyosi** [comment]
Thank you. I'm not familiar with Astro, but it would be great if you can confirm that the upgrade solves the cjs problem there. I will test the Next.js/Remix examples.

**Comment by petyosi** [comment]
Merged that. As far as I can tell, the additional changes are still needed in the Remix environment, the module is still recognized as a CommonJS one. I will keep an eye on this: https://github.com/facebook/lexical/pull/5737, as it might address it.

**Comment by petyosi** [comment]
@david10sing to clarify, this approach: https://github.com/mdx-editor/mdx-editor-in-remix/blob/master/app/routes/_index.tsx seems to work as expected. However, I'm not a Remix expert.

**Comment by david10sing** [comment]
Right I `mjs` file... but yes I think that [fix](https://github.com/facebook/lexical/pull/5737) will remedy the cjs issue.

**Pull request merged**
