### PR TITLE
added functionality: strikethrough, superscript, subscript, highlight

### PR DESCRIPTION
**Pull request by AdityaBorkar**
**added functionality along with the icons and tests:**
strikethrough, superscript, subscript, highlight

**renamed functionality:**
`BoldItalicsUnderlineToggles()` has been renamed to `InlineTextFormattingToggles()` which includes previous functionalities (bold, italics and underline) and new functionalities (strikethrough, superscript, subscript, highlight)

**fixes issue:**
#30

### CODE REVIEW

**Comment by AdityaBorkar** [comment]
This is my first pull request for an open source repository. I would love to hear feedback on it :)

**Comment by petyosi** [comment]
Oh, that's lovely! I've seen that you encountered the combinatory mess related to nested formatting, and the necessity to process the formatting twice. Not pleasant, unfortunately. 

I would rather have the `BoldItalicsUnderlineToggles` kept as is, and introduce an additional toolbar component that includes the strikethrough, superscript, subscript parts. My thinking here is that B/I/U are essential and often used, while the others are much more rarely utilized. This would also make this PR not a breaking change. You can also make the `InlineTextFormattingToggles` accept a parameter that controls which buttons to display. 

Next, Markdown has native support for strikethrough by surrounding the content with `~~` - ~~like this~~. I would rather have that instead of the html tag. You can fiddle with the markdown AST in [this sandbox](https://codesandbox.io/s/ast-playground-r0hvjn?file=/src/index.ts) to see the kind of node the parser will generate.

Finally, I'm using the [material icons (sharp mode, 24px, weight 400)](https://fonts.google.com/icons?icon.style=Sharp), while creating new ones by "butchering" the existing ones where necessary. I think you should be able to find the right ones in the site. Make sure that the svg uses either `black` or `currentColor` ([black works because of this](https://github.com/mdx-editor/editor/blob/main/vite.config.ts#L42)). 

I haven't checked out the code yet. It's good if you create an additional item in `examples`, which demonstrates the parsing of a markdown. In that case, It's good to have an example with nested formatting (the reason for the complex export part). 

I will check the code in further details tomorrow, and let you know if I encounter something. Great work!

**Comment by AdityaBorkar** [comment]
Thanks for the review and recommendations! 😄 

I checked [this link](https://www.markdownguide.org/cheat-sheet/#extended-syntax) and it mentions that Extended Markdown Syntax supports [Highlight](https://www.markdownguide.org/extended-syntax/#highlight), [Subscript](https://www.markdownguide.org/extended-syntax/#subscript), and [Superscript](https://www.markdownguide.org/extended-syntax/#superscript) natively. However, not a many markdown applications support the extended syntax.

How would you plan to implement this functionality?

**Comment by AdityaBorkar** [comment]
I am sorry Petyo, I had something with priority coming up, hence I could not contribute. I will get in touch with you once I am available.

**Comment by kushul** [comment]
Hi,

Is this options available? It would be great if my editor have Subscript and Superscript options on the toolbar 😍

**Comment by petyosi** [comment]
v3.1.0 includes strikethrough, superscript and subscript. https://github.com/mdx-editor/editor/releases/tag/v3.1.0

**Pull request closed without merging**
