### PR TITLE
draft: make panes configurable in SandpackEditor

### PR DESCRIPTION
**Pull request by pixeleet**
Use case: 
Besides configuring the `preset` I would like to be able to control the `panes` presented to the editor.

### CODE REVIEW

**Comment by petyosi** [comment]
Great, I'm happy to merge such change, there's plenty of room for improvement in that integration. Let me know if you need any help.

**Comment by pixeleet** [comment]
I think we should discuss the idea and how it would be best to control which panes are displayed. 
This is a first pass on the idea and as such a draft atm.

**Comment by pixeleet** [comment]
For instance, would it make sense that We have a default setup of Panes that are preset just like the default `sandpackConfig` instead of using boolean flags?


E.g. 
```typescript
const DefaultPanes = forwardRef((props, ref: Ref<CodeMirrorRef>) => (
  <SandpackLayout>
    <SandpackCodeEditor showLineNumbers showInlineErrors ref={ref} />
    <SandpackPreview />
  </SandpackLayout>
))

export const SandpackEditor = ({ nodeKey, code, meta, onChange, focusEmitter, Panes = DefaultPanes }: SandpackEditorProps) => {
  const [editor] = useLexicalComposerContext()
  const [config] = useEmitterValues('sandpackConfig')
  const codeMirrorRef = useCodeMirrorRef(nodeKey, 'sandpack', 'jsx')
  const setActiveEditorType = usePublisher('activeEditorType')

  React.useEffect(() => {
    focusEmitter.subscribe(() => {
      codeMirrorRef?.current?.getCodemirror()?.focus()
      setActiveEditorType({ type: 'sandpack', nodeKey })
    })
  }, [focusEmitter, codeMirrorRef, setActiveEditorType, nodeKey])

  const wrappedOnChange = React.useCallback(
    (code: string) => {
      editor.update(() => {
        onChange(code)
      })
    },
    [onChange, editor]
  )

  const preset = getPresetOrDefault(meta, config)
  if (!preset) {
    throw new Error(`No sandpack preset found for meta: ${meta}`)
  }

  return (
    <SandpackProvider
      template={preset.sandpackTemplate}
      theme={preset.sandpackTheme}
      files={{
        [preset.snippetFileName]: code,
        ...Object.entries(preset.files || {}).reduce(
          (acc, [filePath, fileContents]) => ({ ...acc, ...{ [filePath]: { code: fileContents, readOnly: true } } }),
          {}
        )
      }}
      customSetup={{
        dependencies: preset.dependencies
      }}
    >
      <Panes ref={codeMirrorRef} />
      <CodeUpdateEmitter onChange={wrappedOnChange} snippetFileName={preset.snippetFileName} />
    </SandpackProvider>
  )
}
```

**Comment by petyosi** [comment]
As far as I can tell, what you're doing makes sense *to me* from the angle of the editor being configured to be used for semi-complex code snippets. 

A more complex option is to make that configurable by the user, but it's quite the complexity and it's not worth doing it now. 

I also thought about putting those settings in the preset, but it serves a different purpose in my head. 

Question - I see you have put a read-only flag in there too, what would be the purpose of it?

**Comment by pixeleet** [comment]
> Question - I see you have put a read-only flag in there too, what would be the purpose of it?

 Brain fart, feel free to ignore, realised later that only in the editor view we're controlling panes here, not in the rendered output.

**Comment by petyosi** [comment]
> For instance, would it make sense that We have a default setup of Panes that are preset just like the default `sandpackConfig` instead of using boolean flags?
> ```

👍🏼 the example you've seems quite flexible - if I understand correctly, the developer would be able to completely customize the layout. It can also be a function that accepts the code block meta as an argument and returns a component. This would also allow the usage of certain hooks within the context of the editor.

**Comment by pixeleet** [comment]
I didn't check, how much plumbing it would be to get the `Panes` property where it needs to be.

**Comment by petyosi** [comment]
That being said, if what you have right now works for you I'm happy to take that PR and extend it further with more customization options. The idea of a custom component is not mutually exclusive with the current state of the PR.

**Comment by pixeleet** [comment]
> I'm happy to take that PR and extend it further with more customization options. The idea of a custom component is not mutually exclusive with the current state of the PR.

I think it makes sense to get a simple working version out that fulfils the use case and then we can consider the fancier approach. Sounds good to me.

**Comment by petyosi** [comment]
Great, I will test and merge tomorrow. Thank you for becoming the first contributor to the project ;).

**Comment by petyosi** [comment]
This is merged. Had to make a few adjustments, but I could not push them to the PR (might be a problem on my side). 

Did you enable this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Pull request closed without merging**
